CREATE TABLE IF NOT EXISTS users (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    login VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    PRIMARY KEY(id)
);

ALTER TABLE tickets
    ADD COLUMN created_by BIGINT NOT NULL,
    ADD COLUMN agent BIGINT;

ALTER TABLE tickets
    ADD CONSTRAINT fk_tickets_created_by
    FOREIGN KEY (created_by) REFERENCES users(id);

ALTER TABLE tickets
    ADD CONSTRAINT fk_tickets_agent
    FOREIGN KEY (agent) REFERENCES users(id);
